import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LenisProvider from "@/providers/LenisProvider";
import Navbar from "@/components/Navigation/Navbar";
import Footer from "@/components/Navigation/Footer";

const sfPro = localFont({
  variable: "--font-sf-pro",
  src: [
    {
      path: "../font/SF-Pro-Display-Light.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/SF-Pro-Display-Medium.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../font/SF-Pro-Display-Bold.otf",
      weight: "600",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Saba Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfPro.variable} antialiased`}>
        <LenisProvider>
          <Navbar />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
